### PR TITLE
[0.2.x] Add non-interactive mode

### LINKED ISSUE #64: Prompts does not check for a TTY
### Laravel Prompts Version

0.1.6

### Laravel Version

10.22.0

### PHP Version

8.2.10

### Operating System & Version

Linux 6.4.6

### Terminal Application

N/A, this is about TTYless enviroments and thus no terminal

### Description

Prompts does zero checking if standard input is a tty. Without an interactive tty, which can be caused running commands from cron or in Docker without allocating one, this causes `stty` [here](https://github.com/laravel/prompts/blob/59df38332c5392b10a805f97646b5c5491862486/src/Terminal.php#L42) to fail with `stty: standard input: Not a tty`. Since there is zero checks to see if this was successful or checking that it's on a tty separately, the code always assumes it is on a tty. When [this while loop](https://github.com/laravel/prompts/blob/59df38332c5392b10a805f97646b5c5491862486/src/Prompt.php#L101) is entered, there are no time out checks to break out of the loop, nor is there a there something to slow it down since `fread(STDIN, 1024)` [here](https://github.com/laravel/prompts/blob/59df38332c5392b10a805f97646b5c5491862486/src/Terminal.php#L28) instantly returns zero length string with out a tty (assuming nothing has been piped in there, or has otherwise been drained).

This has the following consequences, assuming that scheduled commands in cron trigger this, 100% CPU thread utilization per instance started and slow memory exhaustion as concurrently running commands pile up.

There are a few ways I can see fixing this, from detecting the lack of a TTY & throwing an exception to end everything, to accepting default options. My assumption is detect and throw is the better one, but I'm happy to be proven wrong.

### Steps To Reproduce

1. Add a command that uses ` Illuminate\Console\ConfirmableTrait` to the scheduler in Laravel, while forgetting to set `--force` for production
   * Alternatively, upgrade a package you already have a scheduled command for that migrated to using `laravel/prompts`, and not realize the consequences that change causes.
2. Wait for schedule to execute the command without a TTY.
   * Alternatively, you can run a command in your shell this way to execute it without a TTY attached: `(setsid php artisan activitylog:clean) </dev/null`
   * Yes, the parentheses are needed, use of the subshell avoids `setsid` forking and going into the background, and the `/dev/null` redirect is to remove keyboard input, like it would be while cron runs.
3. Profit!

### PR DESCRIPTION
**Pull request by jessarcher**
This PR introduces a non-interactive mode for Prompts.

When Prompts are non-interactive, they will attempt to return the configured default value instead of prompting. Most prompts have a safe default when none is provided. An exception will be thrown if the default value does not pass any validation checks.

This is useful when prompts occur in a non-interactive environment, such as a scheduled task, queued job, CI, or deploy script.

The behaviour is currently mixed, depending on the scenario. #63 prevented prompts from waiting indefinitely for input when the fallback was not triggered, but everything now depends on the fallback to handle non-interactive mode. When using a Symfony fallback, there are some inconsistencies. For example, the `choice` component doesn't allow you to select nothing in interactive mode but will return `null` in non-interactive mode. With this PR, the fallbacks no longer need to be used for non-interactive mode - just for Windows and when testing (for now).

This is a breaking change because Laravel depends on the fallback when running tests and the non-interactive mode will take over in a CI testing environment. If we release this change in `v0.2`, Laravel can update its version constraint and ensure interactive mode is enabled when testing. The companion PR is at https://github.com/laravel/framework/pull/48468

In the future, I would like to prevent the need for fallbacks when testing so that fallback mode is only required for Windows environments (and maybe that can even be solved with #17).

This also paves the way for #57, which needs to know when Laravel commands are explicitly told to be non-interactive (via the `-n` argument), regardless of the presence of a tty.

Fixes #64

### CODE REVIEW

File: src/Prompt.php [hunk 1]
```diff
@@ -73,6 +74,12 @@ abstract public function value(): mixed;
      */
     public function prompt(): mixed
     {
+        static::$interactive ??= stream_isatty(STDIN);
```
Comment (jessarcher) [inline src/Prompt.php:77]: This will break existing Laravel applications when testing console commands in a CI environment. They won't fall back to the Symfony implementation, which is required for the test assertions to work.

It can be solved with a small change in the framework, but that won't help if users have this version of prompts with a slightly older version of the framework.

The solution might be:
* Release this as a breaking change (v0.2.0) to prevent current Laravel installations from installing it.
* Update the minimum required version of Prompts in the framework and add code to set interactivity mode when required.

Alternatively, we could default this to `true` for the time being to maintain existing behaviour and then make the breaking change later.
